jms_serializer:
    visitors:
        json_deserialization:
            options:
                - JSON_UNESCAPED_SLASHES
                - JSON_PRESERVE_ZERO_FRACTION
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'